### ISSUE TITLE
Looping at negative playback rates doesn’t work in 264.sfplay~

### ISSUE THREAD

**Issue by delucis** [mus264/264-tools#20]
Might be a regression from #16, but in any case, when `264.sfplay~` is playing at a negative rate (i.e. in reverse), it reaches the start of the file and stops playing even when looping is turned on.

**Comment by delucis** [comment]
Confirmed that this is a regression introduced by #16, probably by switching to using `1` as the play message instead of defining a cue and using `2` as a play message.

**Comment by stefanprins** [comment]
Hey chris,

I hope you’re well. 
I keep on receiving these mails, could you take me off the list (though it does feed
My nostalgia!)
Best!
S

Sent while on the road.
