### ISSUE TITLE
Create breakpoint function module

### ISSUE THREAD

**Issue by delucis** [mus264/264-tools#6]
Create module to allow creation of breakpoint functions to control module parameters.

![Whiteboard notes from 31/8/2016](https://cloud.githubusercontent.com/assets/357379/18140399/5ce5a9ac-6f83-11e6-8431-5a9955a8eddd.png)

**Comment by delucis** [comment]
@hanstutschku Here is a sketch of a new `264.line` module that would allow students to draw functions, scrub through them, trigger them with a given duration, and loop them:

![ezgif com-optimize](https://user-images.githubusercontent.com/357379/51810593-d49c2900-2276-11e9-9b4c-43644eb7fd7b.gif)

Any immediate thoughts? I’m trying to keep it to this half-module size so lots of functions don’t take up too much space, but it’s a little tricky squeezing everything in nicely. What kind of features would you expect? Does the behaviour above seem good?

**Comment by hanstutschku** [comment]
Hi Cris,

Love it! More space might be better though. 

Hans

**Comment by delucis** [comment]
@hanstutschku @jsbean Here is a screencap of the updated `264.line` prototype:

![ezgif com-optimize 1](https://user-images.githubusercontent.com/357379/51879783-c582ad00-2342-11e9-8c6a-ae84497a4eaa.gif)

Instead of editing directly in the module, clicking on the function brings up a big editing window. I also updated the playback animation to be a bit cleaner.

One quick practical question: right now the playback duration range is on the shorter side (40ms–30 seconds). Hans, you mentioned today an example of a three-minute function. What is the ideal range of durations for these functions? (Bearing in mind that these should also be mappable to a MIDI fader, so too big a range might also have drawbacks in terms of fine-grain control.)

**Comment by hanstutschku** [comment]
I like the big editing window.
Would it be possible to expose the domain to the user, e.g. we can decide for each instance what the duration might be?

**Comment by delucis** [comment]
There’s a duration number box on the left that allows them to choose how long it is. The question is what range of durations are realistic for a MIDI fader. Right now I have it set up between 40 ms and 30 seconds, but given your comment today, I thought maybe the usefulness is more in the 2s to 3 minutes range perhaps. What range do you most often use in your patches?

**Comment by hanstutschku** [comment]
There are very different uses. Imagine you just want a crazy fast filter modulation, but not just random.
Let’s say you make 4-5 functions and then trigger them in some order.
Those might be under one second long.

Now think about a slow evolution of a filter parameter over 2-3 Minutes - not necessarily controlled with a midi fader.

**Comment by delucis** [comment]
OK, I’ll set the range for 40–240,000ms for now with a nice quartic fader law so from their MIDI controllers they can still select a shorter duration with good control, and sacrifice a bit of control for the longer durations. Thanks!

**Comment by jsbean** [comment]
As I commented on in the PR, this works great as implemented.

Is there a way to intercept the **⌘-c** and **⌘-v** keystrokes for the copy and paste functionality?

**Comment by jsbean** [comment]
Totally reasonable if this is out of scope: what would be the difficulty of implementing a click-and-drag selection box? This could potentially enable copying-and-pasting, reversing, translating, and/or deleting a selected subset of the total set of points.

I assume this would add considerable complexity to the underlying model, but the analog to automation within a DAW is so strong here. The interface already present is so cleanly laid out, the headroom for added functionality seems quite high (without things getting clumsy).

**Comment by delucis** [comment]
Thanks for taking a look.

I just implemented keyboard shortcuts (also for undo/redo), but Max triggers the system alert/error sound when using standard shortcuts (e.g. <kbd>cmd + c/v/z</kbd>) in a locked patcher. @hanstutschku do you know of any way to avoid that with default keyboard shortcuts? Is the error sound an acceptable trade-off for these keyboard shortcuts? Alternatively, I could use different shortcuts, e.g. <kbd>c</kbd> instead of <kbd>cmd + c</kbd> for copy, but that would be a less familiar user experience.

Click-and-drag would be nice, but close to impossible with the tools Max offers. The only additional UI/editing feature I can easily conceive of building is a kind of “hand” tool that would move all points by dragging.

**Comment by hanstutschku** [comment]
Unfortunately, I don’t know a way to overcome those keyboard shortcut limits.

**Comment by delucis** [comment]
Thanks Hans, that’s what I expected. In that case, I think I’ll skip keyboard shortcuts unless you think some alternative shortcuts would be useful.

Here’s a quick demo of the final editor including a new “move mode” for dragging the points:

![ezgif com-optimize](https://user-images.githubusercontent.com/357379/54473295-09881f00-47d6-11e9-8ab8-f1258b407986.gif)

**Comment by delucis** [comment]
Finally merging this now. I have also added a “draw” mode to the editor.

![function editor demo](https://user-images.githubusercontent.com/357379/54886438-4a2f0a80-4e5e-11e9-8e52-f5d01f55675c.gif)
